# Generated by Django 2.2.13 on 2021-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='event',
            name='withdraw',
        ),
        migrations.AddField(
            model_name='participant',
            name='withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
