# Generated by Django 2.2.13 on 2021-01-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210122_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='withdraw',
            new_name='attended',
        ),
    ]
